kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: regional-sc
provisioner: kubernetes.io/gce-pd
reclaimPolicy: Retain
parameters:
  type: pd-standard
  zones: us-west1-a, us-west1-b
  replication-type: regional-pd